### ISSUE TITLE
Open button does not work in Firefox 105.0.1 with Windows 10

### ISSUE THREAD

**Issue by AndreaBellora** [sienori/Tab-Session-Manager#1085]
Dear Tab Session Manager team, 
first of all thanks for this amazing extension. It has saved a lot of my time through the last year or so (since I discovered it). 
I'm writing you because, since a couple of days, the 'Open' button in the toolbar widget for Firefox has stopped working. 
I'm currently running on Windows 10, with Firefox v105.0.1, but the same happens on my VM with Ubuntu 20.04 and Firefox 105.0. 
I already tried uninstalling and reinstalling the extension and scanning for updates, unfortunately without success. 
Do you have any further suggestions to debug?

**Comment by jacquesvandermerwe** [comment]
I can confirm it is exactly the same behaviour on Mac Monterey 12.6. Followed the same steps as the OP above and the exact same issue. Deleting and Saving works fine

**Comment by FernandoBasso** [comment]
I my case, I'm on Arch Linux and the problem also started since Firefox v105. My Firefox config for “homepage and new windows” had the string "cache". I think I typed some search at some point, but instead of typing in the search box, I accidentally typed it in there :sweat_smile:.

![image](https://user-images.githubusercontent.com/6560620/194701164-74141d7a-00ca-4ea4-9bfb-2cf0180c78eb.png)

Still, for some reason the problem did not show up until Firefox v105. I'm glad your comments led me to finding it out. Thanks.

@sienori Thanks a lot for your work in this extension.
