### ISSUE TITLE
Can You have an option to automatically reopen last session?

### ISSUE THREAD

**Issue by walkerpbus** [sienori/Tab-Session-Manager#118]
My wife is not very computer literate but likes Facebook. I just had 2 restarts this day & my wife opened Facebook without restoring several times so I had to go back several sessions to get a decent

**Comment by ElhemEnohpi** [comment]
Go to: Firefox Preferences/Options -> General -> Startup
Check: When Firefox starts: Show your windows and tabs from last time
Does that solve your problem?

**Comment by hejops** [comment]
I'm pretty sure the whole point of this extension is to _not_ have to use that option. That option doesn't achieve what he wants anyway.

**Comment by sienori** [comment]
I added the option in version 1.8.0.
https://github.com/sienori/Tab-Session-Manager/commit/4fd6aa64e7d691ae7c625075fa559ffdfefaa83f

**Comment by ElhemEnohpi** [comment]
@hejops I think the point of this extension is to have the ability to save and restore multiple different named sessions, as well as to have multiple backup versions. Those are good features, but otherwise the native session restore is superior in many ways. Because it's built-in to Firefox, it's able to fully restore all data from a session, including things that Web Extensions don't have access to, like tab history and so on. I'd suggest that people use both. Great that sienori added the option to do it through Tab Session Manager, but for the requested function to regularly "automatically reopen last session", I'd recommend the built-in one.

It sounds to me like the "show my windows and tabs from last time" achieves exactly what @walkerpbus requested in the title, to ""automatically reopen last session", though it's a little difficult for me to understand what he wrote. What makes you think it doesn't?

**Comment by hejops** [comment]
> I'd suggest that people use both.

Pretty sure that's not possible. It's either the native session manager or this. This was also the case for the old Session Manager extension.

**Comment by ElhemEnohpi** [comment]
You're wrong on both accounts. I know because I actually do both of those things.

These are my settings for Tab Session Manager:

![screenshot_242](https://user-images.githubusercontent.com/23618559/34254026-66ad69d6-e64a-11e7-80c2-7edb93ae1d0e.png)

Built-in session restore ("show your windows and tabs from last time") takes care of re-opening the previous session on startup, including all session data such as tab histories, etc., which Tab Session Manager can't do. Tab Session Manager is there in case I want to save a particular session under a name to re-open in the future, or if I want multiple auto-saved sessions to choose from after a crash, etc.

With legacy Session Manager, it's in fact required to use these settings if you use Window Sessions, due to [bug 26130](https://www.mozdev.org/bugs/show_bug.cgi?id=26130) in Session Manager:

![screenshot_240](https://user-images.githubusercontent.com/23618559/34253735-2366c722-e649-11e7-8c2b-9bdae9bd2a51.png)

**Comment by hejops** [comment]
Hmm, well you have a point. I have realised, however, that the "show your windows and tabs from last time" option does not work when "Browsing & Download History" is cleared after closing.

**Comment by Grossdm** [comment]
@hejops, hasn't the problem of losing saved sessions been solved since [Version 3.0.0](https://github.com/sienori/Tab-Session-Manager/releases/tag/3.0.0)?

**Comment by sienori** [comment]
This issue seems to be solved.
