### ISSUE TITLE
Tab Suspender bug

### ISSUE THREAD

**Issue by zeus2615** [sienori/Tab-Session-Manager#132]
1. clean firefox profile
2. installtab session manager  and "tab-suspender"
3. open tab with url "www.bing.com"
4. right click and suspend tab
5. open tab session manager save session
6. open saved session
7. click the suspend tab page
the saved tab cannot open normally with url like
"moz-extension://4034d1e8-aae1-ca46-80b0-13c62a16142a/data/suspend/index.html?title=%E5%BE%AE%E8%BD%AF%20Bing%20%E6%90%9C%E7%B4%A2%20-%20%E5%9B%BD%E5%86%85%E7%89%88&url=http%3A//www.bing.com/&favicon=http%3A//www.bing.com/sa/simg/bing_p_rr_teal_min.ico"
and it never go on open it

I am not sure it's a bug of suspender or session-manager, so I decide to report it to both developer. 
THANK YOU for your working on new firefox addons

**Comment by sienori** [comment]
It is a problem of Tab Suspender.


1. You restore session with TabSessionManager
2. Tab Session Manager try to open the Tab Suspender page
3. Tab Session Manager opens the replace page
 (According to the specification of Web Extensions, add-ons can not open pages of other add-ons)
4. When focus shifts to the replace page, Tab Session Manager redirects to the Tab Suspender page

5. Tab Suspender page is displayed
6. When you click the suspend page, Tab Suspender go back to previous page
7. Tab Session Manager's the replace page is displayed
 (Once you select another tab and move focus again, it returns to 3.)


The cause is that Tab Suspender performs a page back operation in 5.
Tab Suspender should redirect based on parameters, not page back.

**Comment by sienori** [comment]
I made it impossible to access the lazy loading page from the back button. It work in FF 57 or later. 03b7c87
This change solved the problem of Tab Suspender.
