### ISSUE TITLE
Restoring session changes tab order

### ISSUE THREAD

**Issue by rayman89** [sienori/Tab-Session-Manager#140]
Restoring a session changed the tab order from 1 2 3 to 3 2 1

**Comment by 1RonRock** [comment]
I am having this same issue. I am also unable to open the saved tabs. When I try to open them many will not open, I get a blank screen.

**Comment by sienori** [comment]
@1RonRock I fixed the problem that the replacement page can not be replaced.
https://github.com/sienori/Tab-Session-Manager/commit/ca58887f225c8152de08aca48974f26962b77cfd

This change also includes improved tab sorting algorithms.
If it is not improved, it may be interfering with another add-on or Firefox setting

**Comment by gamingexpert13** [comment]
I have the same problem, but it's because I have the extension "Tab Open/Close Control", which gave me the option to open new tabs next to the current tab instead of at the end of the list. Unfortunately when this is enabled, Tab Session Manager doesn't realize it, and still opens the tabs as if each new one will be at the end of the list, so they end up opening in reverse order. I'm not sure if there's a way to make an option in Tab Session Manager to fix it, but I'm thinking there could be an option to restore the saved tabs in reverse order (bottom to top) and then the extensions would probably cancel each other out and everything would open correctly.

**Comment by rayman89** [comment]
They open properly now but like @gamingexpert13 says when using addons that change where new tabs open like "open tabs next to current" and "Tab Open/Close Control" because tab session manager seems to open tabs differently than 1 ->2 ->3 tabs end up being disordered.

This are the test tabs on a new clean profile with only session manager and "open tabs next to current" addon

![image](https://user-images.githubusercontent.com/5449042/36155621-7bb3885e-109a-11e8-8e1f-e369d3993cfa.png)

And this is after restore

![image](https://user-images.githubusercontent.com/5449042/36155658-9035e5b0-109a-11e8-845d-12e2d73b00ed.png)

**Comment by devanes** [comment]
Same issue with  "open tabs next to current" . I now have three windows with hundreds of tabs in the wrong order, and it's not just reversed. I probably also depends on which tab was active when the session was stored.

And to further increase my problems: my session list is suddenly empty, so disabling  "open tabs next to current"  and doing a new session restore has become impossible. I'll have to manually reorder the tabs. This is a big bummer.

**Comment by sienori** [comment]
I fixed this issue. https://github.com/sienori/Tab-Session-Manager/commit/1b68e8753f08e74691844e4935d9a6d59e70ff6c
