### ISSUE TITLE
All sessions database lost

### ISSUE THREAD

**Issue by resilientCoder** [sienori/Tab-Session-Manager#153]
Initial report.

All sessions apparently lost.

that may mean ther eis either:
a.) database/filesys or whatever mechanism  corrupted, or
b.) filesys corruption, need to chkdsk /f

will get back after thorough chkdsk

this is after putting laptop to unplugged, really mobile mode, and seeing nothing unusual except now last minute black screen on restoring hibernated windows.

**Comment by sienori** [comment]
The problem of session file corruption has been reported by several people.
I think that it probably happens when Firefox or the PC is terminated while writing to the session file.
In order to deal with this problem, I'm planning to implement the backup function to the cloud.

**Comment by RobertAb1** [comment]
Is everything saved in 1 file? Maybe more files should be used and each time TSM should write to the current (last) file something like checksum (like in WinRAR). Then on the start, TSM should check if checksum is correct - if not it should use older file.

**Comment by Verequus** [comment]
There is at least a way to manually backup sessions and to restore them afterwards. Not convenient, but helps against losing everything at once.

**Comment by sienori** [comment]
I implemented the function to save the backup.
The save destination is only Firefox default download directory.
https://github.com/sienori/Tab-Session-Manager/commit/96e76b0d8c79ed0fe08af974e03fcdf0a72bfcfa

**Comment by gamingexpert13** [comment]
I had the same problem years ago with my last session manager, and now it happened on this one too. With any session manager extension, people use it as a backup solution, and a single file containing everything is not an effective backup solution (and the average user isn't going to export his sessions manually when he assumes the extension takes care of protecting his sessions automatically). I'm not sure how extensions in the past did it (for example Session Manager, SessionSaver, and Tab Mix Plus), but I can think of a couple ways. Instead of continually overwriting the same file, write a new file each time, and delete the oldest once you hit a limit of something like 15. Even if it's too hard to use a checksum or fall back to an old session save if the most recent fails to load, with this sort of setup, we can at least manually restore all of our sessions if one happens to get corrupted (from a power outage or something).
If it's more efficient to overwrite or modify an existing file instead of creating new ones, you could alternate or cycle through multiple session saves to modify/overwrite instead of creating and deleting every time. 
I'm sure there's a number of other ways too, and a cloud backup might work, but that might end up being more complicated, and might fail if someone has connection problems or something. 
Anyway, thanks for your work on this extension! Even though I lost my saved sessions, I can't be mad, because you're doing all this coding for free.

**Comment by RobertAb1** [comment]
Yes, each session in Session Manager was automatically or manually saved in separate files.

**Comment by sienori** [comment]
@gamingexpert13 
In WebExtensions, it is impossible to manage each session as one file.
It can only save all sessisons to storage.js using the storage system.
The add-on can save copy of session as the backup but can not automatically retrieve the contents of the saved file.

Management of backed up files is done using download history.
If the user deletes the download history, Tab Session Manager will not be able to manage files.
Therefore, if the add-on saves the backup file for each session, unnecessary backup file increases as garbage.
So, I will not change the backup specification.

Also, restoration of storage.js.corrupt is probably not possible. Sorry.

**Comment by irvinm** [comment]
I probably mentioned this in another issue, but I simply wrote a batch file that is kicked off from "task scheduler" that makes a backup of the storage.js by copying and appending the date-time.  The script runs every 4 hours and keeps 10 backups and deletes anything older than that.

I have had Firefox get corrupted to the point where things were reset and\or even assigned get UUIDs for addons.  In those cases, the only way for me to retrieve my previous tabs was thru history and that is a real pain.

By backing the file up itself, even if there is a major issue that corrupts storage.js, you can hopefully just restore an old copy and not lose too much.

Thank you @sienori for your work on this add-on.  I think it works really well within the constraints of the new APIs.  Now if they could just finish up supporting "discarded" in browser.tab.create() we would really be set with a native implementation when restoring a session. (https://bugzilla.mozilla.org/show_bug.cgi?id=1378647)  Shame there doesn't seem to be any current momentum.

**Comment by sienori** [comment]
Replacement with IndexedDB is complete. 22d3f06
Sessions will not disappear from the next version.
