### ISSUE TITLE
Sessions are not displayed when the filter is empty

### ISSUE THREAD

**Issue by Verequus** [sienori/Tab-Session-Manager#187]
I have saved a backup some time ago. If I use the restore functionality, it says that 22 sessions have been loaded, but no single of them is actually accessible afterwards.

**Comment by maskatuoklis** [comment]
Same here. Two days ago I have shut down Firefox, then opened - no sessions were saved. I exported the session file, then imported again (by the way, I've checked - there were many entries in that file), but the plugin doesn't show any saved sessions. Reinstalling of plugin didn't work.

**Comment by sienori** [comment]
Please make sure that the category filter at the top of the session list is "All".
You should see hidden sessions.

**Comment by maskatuoklis** [comment]
Thanks, I didn't know / notice the filtering feature, now it's working ;)

**Comment by Verequus** [comment]
That was the reason for me, too. I checked the release notes and I saw no mention of such a change. Would it be possible if the dropdown box shows the used filter by default?

**Comment by sienori** [comment]
@Verequus 
Normally, the filter used last time is displayed.
However, due to the effect of changing the internal tag in version 2.1.0 (https://github.com/sienori/Tab-Session-Manager/commit/008c14682d4aacbe967c41f742695adda12465a4), the problem occurred that the filter become empty when updating to ver 2.1.0.
I will fix this problem.

**Comment by sienori** [comment]
I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/08460451fb5f0e4454b241562940cbc5449d9059
