### ISSUE TITLE
Option to specify backup save folder

### ISSUE THREAD

**Issue by boistordu** [sienori/Tab-Session-Manager#189]
Could be great to designate in the settings where to save the session since you seem to have problems to keep the session without erasing it @ each update. OR maybe add an option to export automatically the session to a folder each interval of time

**Comment by hauschke** [comment]
Maybe it would be possible to use a SQLite db to store the information?

**Comment by boistordu** [comment]
yeah but again, with the risk to erase the content of it if you are not cautious enough in the code.
Better to give the job to the extension to export automatically for backup purposes.

**Comment by sienori** [comment]
It is possible to add an option to change the backup location.
However, since it is limited to the download folder and below, I think that option is less necessary.
(Current default folder: [download folder]\TabSessionManager - Backup)

I plan to implement a function to store backups each interval of time.

Also, I will update it to save the sessions in IndexedDB.

**Comment by syldub69** [comment]
Backup location cannot configured to be a specific folder outside of default default folder?
For instance, my default download folder is D:, but I would like to store the Tab Sessions Manager backup in C:

**Comment by sienori** [comment]
@syldub69 
It is impossible to save backup outside the download folder.

https://developer.mozilla.org/ja/Add-ons/WebExtensions/API/downloads/download
> Absolute paths, empty paths, and paths containing back-references (../) will cause an error.

**Comment by syldub69** [comment]
You told since the backup location is limited to the download folder and below, it is less necessary... but I think the ability to specify the download folder inside the default Firefox download folder is interesting, for instance: [download folder]\Backups\Firefox\TabSessionManager - Backup
Let me explain why this could be interesting in my case: my Firefox download folder is the root drive D:. I would like to store the backups in a subfolder of this root drive.

**Comment by sienori** [comment]
@syldub69 
I will consider adding options.
Thanks!

**Comment by netllama** [comment]
Earlier in this thead there's a comment that its impossible to save the backups outside of the Download directory.  However, I have no Download directory, and instead, I'm stuck with the backup directory getting created in my $HOME (I'm using Linux):
```
$ pwd
/home/netllama
$ ls -d TabS*
TabSessionManager - Backup
```
I can file this as a new bug, but I wanted to note, that the original statement regarding the location of the backup directory is not accurate.

**Comment by sienori** [comment]
I added the option to specify backup location. https://github.com/sienori/Tab-Session-Manager/commit/0f67d9aed72b0352a018bc0e76a6bb516d0a6453
![save location](https://user-images.githubusercontent.com/29514424/38146159-b9998de2-3487-11e8-8258-b7d08d330f6d.PNG)

**Comment by sienori** [comment]
@netllama 
I think $HOME is specified as your default download directory.
The download directory can be changed from firefox options.
![download location](https://user-images.githubusercontent.com/29514424/38146269-40773fe4-3488-11e8-8b42-f8fd076d8b48.PNG)
