### ISSUE TITLE
feature request: save session on URL load, new tab open

### ISSUE THREAD

**Issue by maximloginov** [sienori/Tab-Session-Manager#190]
I really love the "Auto save" option, although saving session every X minutes may waste the a lot of disk space when firefox is idle e.g. user works with other programms without closing firefox. It would be nice to avoid this, and in addition to option "Save the session regularly", it would be nice to save session on events like URL load and reload, new tab or window open etc. Would it be possible?

**Comment by sienori** [comment]
For "Save the session regularly", sessions are not saved unless the tab has been changed.
In other words, sessions are never saved when Firefox is idle.


>save session on events like URL load and reload, new tab or window open etc.

Automatic saving on each events will consume more resources.
Internally, "auto save - window was closed" is saving session on each events.
In fact,, a performance decline is reported. https://github.com/sienori/Tab-Session-Manager/issues/171
(In order to solve this problem, I will implement it using IndexedDB in the future.)
