### ISSUE TITLE
Feature request: Allow changes to backup location

### ISSUE THREAD

**Issue by sNiXx** [sienori/Tab-Session-Manager#219]
I like the automatic backup creation, but it would be a lot nicer if we could change where they are stored.

**Comment by WebSkater** [comment]
This could be very helpful for me too. Where will TSM store backups if for downloads in firefox no location is set = Always ask me where to save files ?!

**Comment by sienori** [comment]
I added the option to specify backup location. 0f67d9a https://github.com/sienori/Tab-Session-Manager/issues/189
![save location](https://user-images.githubusercontent.com/29514424/38146159-b9998de2-3487-11e8-8258-b7d08d330f6d.PNG)

**Comment by netllama** [comment]
While its great that this feature is now available, it has an awful bug where it converts dots to dashes.  On any Unix based system (literally anything that is not MS-Windows), starting any object with a dot (.) makes it hidden by default, which is the default expected behavior for stuff like configuration files & directories.  However, any time I enter a dot (such as ```.TabSessionManager_Backup``` ), it gets auto converted to a dash (```-TabSessionManager_Backup```).  This is wrong for many reasons, including the fact that dashes are treated as special characters, meaning that any interaction with this dash pre-pended directory now requires special handling to interact with it.

**Comment by sienori** [comment]
@netllama 
Due to firefox restrictions, it is not possible to generate a file whose name begins with a dot.
For that reason I am prohibiting entering dots.

**Comment by netllama** [comment]
@sienori   specifically which firefox restrictions are you referring to?

**Comment by sienori** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download
>Absolute paths, empty paths, and paths containing back-references (`../`) will cause an error.


Actually, if you specify a filename that starts with a dot, an error will occur and the file will not be saved.
I confirmed that file saving failed on Windows and UNIX.

**Comment by netllama** [comment]
But a single dot is not a 'back reference', nor is it an absolute path.  This seems like a bug or a spec violation if they are throwing an error over a filename that starts with single dot.

Regardless, changing a dot to a dash is not desirable behavior.

**Comment by sienori** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=753267#c7
>This prevents the user from manually choosing a special file name, but it's safer from a security standpoint
It's also safer for non-technical users, to avoid creating a hidden file inadvertently. 

It seems to be a limitation for security.
I can not do anything ...
