### ISSUE TITLE
feature request: save-session for this window only

### ISSUE THREAD

**Issue by meoso** [sienori/Tab-Session-Manager#30]
When I have multiple windows open, i use them as a subject-container so to speak.  When I save a session, i'm expecting to only save the window i'm in; However, it instead saves all windows, which i do not want.

**Comment by sienori** [comment]
I would like to implement it with #14.
It will take some time because UI adjustment is necessary.

**Comment by ffreeman21** [comment]
I'd like to strongly endorse this request.  I've been using the former Session Manager for several years.  When I want to save a window, I ALWAYS have at least two windows open (often more) - my 'daily' active window (which is auto-saved by Firefox (using Firefox internal settings) as my last window to be closed & then opens when I restart Firefox) & my current 'project' session(s), which are the ones I have previously saved in Session Manager, and would now like to use Tab Session Manager for.  Meanwhile I'm sticking with Firefox 56!

I note you comment that this will "take some time" - does that mean weeks, months, or what?

In any case, many thanks for your efforts in replacing the former Session Manager!

**Comment by wbt** [comment]
I'd also like to endorse a request to have a UI option for "Save current window."  Saving the full session (all windows) should be the default and easiest, but saving just one window to a session file is a feature I miss from the old session manager.  Thanks for your work replacing it!

**Comment by ffreeman21** [comment]
I've previously strongly endorsed the request for "Save ONLY CURRENT Window" - that is how I ALWAYS use the old Session Manager.  Whether the default is to save Current Windows or Save full session should be a setting for the user to choose.  I'm still using Fx 56 and using the old Session Manager until I can (1) save individual windows, and (2) save the windows in Groups / Categories because I have so many Windows saved and am continually using Session Manager throughout the day.  The product is useless to me until I can save individual windows.  I'm soon seriously going to have to consider moving to an alternative browser in order to get the desired functionality.
Any indication of time scale for these improvements, please?

**Comment by lucasama** [comment]
Please, I also need this functionality. I currently have a mess of hundreds of tabs opened all the time just because I cannot organize them in Windows. I never cared about saving the whole session of opened windows. Each window should be a session on its own, like with Session Manager. Thanks!

**Comment by sienori** [comment]
Sorry it took so long. I implemented it.
https://github.com/sienori/Tab-Session-Manager/commit/5ede5f3797fa013ccd6515253c7e3e78448c093e

**Comment by ffreeman21** [comment]
Thanks.  This is one of the key features that I needed and may be enough to let me move to FF57.  At the moment I'm still using FF56 with the old Session Manager because of the previous lack of this (and other) features.  My other key 'want' is to be able to store the sessions in Groups / Categories, but I might overcome that by prefixing the Session names with the respective Category name.

**Comment by tbertels** [comment]
With the new version, you can also add tags, which work as Groups / Categories but with more possibilities.

**Comment by meoso** [comment]
request: option to set this as default behavior?
