### ISSUE TITLE
Export/import settings

### ISSUE THREAD

**Issue by nollinvoyd** [sienori/Tab-Session-Manager#350]
Firefox 63.03, Windows 10 Pro

Export/import settings.  I suppose this may have been requested before.  It would be a nice option.

**Comment by sienori** [comment]
Export and Import can be executed from the option page "sessions".
![Option page](https://user-images.githubusercontent.com/29514424/49360400-675b9400-f71c-11e8-8a24-963461603657.PNG)

Also, please select export of individual session from session menu.
![Menu](https://user-images.githubusercontent.com/29514424/49360403-67f42a80-f71c-11e8-8b8b-7381d0a80c1a.PNG)

**Comment by nollinvoyd** [comment]
I was referring to the export/import of "Settings", not sessions.

**Comment by sienori** [comment]
Sorry I misread.
I will implement that option in the future.

**Comment by Grossdm** [comment]
> Firefox 63.03, Windows 10 Pro
> 
> Export/import settings. I suppose this may have been requested before. It would be a nice option.

I was actually confused when I tried to export my settings.
It seems that this means that it is not possible.

With TSS _not syncing its settings_, export/import of settings is **needed very much**.

Thank you!

**Comment by rddim** [comment]
+1

**Comment by nihaals** [comment]
It would also be useful if you could sync these settings with the browser's built in sync system (and as a bonus Google Drive)

**Comment by Mayurifag** [comment]
I would like to see this feature so much, so my thumbs up for here @sienori 

There are too much settings that are not optimal for my usage after ext installation and it always blows my mind to set the things up after new browser installations.

I dont think its very needed for the first iteration to add these settings into browsers built-in system or Google Drive (as mentioned by @nihaals ) but if so, I would also like to have webdav system then. But still, having import/export settings thing via configuration file is an absolutely must-have for any extensions that need further interactions at settings page.

**Comment by nihaals** [comment]
> I dont think its very needed for the first iteration to add these settings into browsers built-in system or Google Drive [...] but [...] having import/export settings [...] via [a] configuration file is an absolutely must-have

I partially disagree. Files are definitely useful, especially for cross-browser import/export, but I think using the browser's sync system would be more helpful for a wider range of people. In my opinion, the main use case is installing a browser and wanting everything to just work, instead of having to go through each extension and setting them up again, which is especially hard if the extension doesn't open a tab on install, causing you to have to go through your entire installed extensions list.

In this scenario, browser sync would completely avoid this problem (especially if either a message is shown that settings were imported or the tab isn't opened on install), while a file would just mean you don't have to think about every setting again, but you would still need to do a manual process to setup the extension. Google Drive makes this easier, but there is still configuration post install of logging in and possibly selecting which version to use, remote or local.

**Comment by Mayurifag** [comment]
Oh, I see your position. Its not my cup of tea though, because I dont trust mozilla services including sync, -- I dont know how is it working internally and dont know how it will be changed in future, so I save backups into my cloud or github. 

The thing I wished to say is not about discussions of best saving mechanism. I just pointed, that this task may be divided into at least three iterations:
- Import/export saving backup file
- Saving backup file into mozilla sync
- Saving backup file into gdrive/webdav/dropbox/ you name it

And to have least possible development procrastination its better to realize import/export as first step and thinking about sync options further. Sorry for any misunderstanding :)

**Comment by sienori** [comment]
I have implemented a settings import/export function. https://github.com/sienori/Tab-Session-Manager/commit/be537832b650148a54b193488e4afe598d139159
Thanks for your patience!
![image](https://user-images.githubusercontent.com/29514424/129328269-9c69ba91-a8e4-4f48-9e2c-970d7bbf6471.png)
