### ISSUE TITLE
Location of Session store in Portable Firefox.

### ISSUE THREAD

**Issue by Califauna** [sienori/Tab-Session-Manager#429]
Hi,

I recently found this extension wasn't working and had to reinstall it. Reinstalling it I found all the sessions gone. 
In the options of storing the sessions in a backup file under the download folder. However, this is creating the backup at start up as indicated on my system.

There is no file ' storage.js' in my profile folder on my system not in the ' browser-enstention-data' folder.  

Where else might it be located so I can set up a backup of the file using backup software?

Thanks.

**Comment by nollinvoyd** [comment]
Those who don't back up there data will eventually come to regret it.  I hope that's not the case for you.

Is this the setting you are referring to ("creating the backup at start up")? 

![TSM](https://user-images.githubusercontent.com/20844322/62966449-eb8e0d00-bdbb-11e9-9c6d-5c5f6eb7a299.png)

If it is enabled as you see it here, the session backup file is located in wherever you have the "TabSession Manager - Backup" folder located.  Go to settings > sessions, besides "import" select "browse" and navigate to the "TabSession Manager - Backup" folder, and select whichever one of the several backup files that have been saved there you wish import.

BTW, the entire Firefox profile folder is portable, and can be backup up, manually (copy/paste) or with backup software.  If you're interested in learning more about it, and a lot more valuable information about managing Firefox, see this

http://forums.mozillazine.org/viewtopic.php?f=23&t=2821799

Also, if I want to easily and quickly transfer a single session to one of my other profiles, I just copy the sessionstore-backups folder, sessionCheckpoints.json, sessionstore.js, and sessionstore.js, and replace the matching items in the target folder.  

I don't have a "storage.js" file.

**Comment by Califauna** [comment]
Firefox was set to ask for download location every time. I set it to download to the windows downloads folder. Restarted firefox. No tabs session manager folder was created in the downloads folder.

So, changed the name of the folder in the little box in the session manager backup settings section.  Restarted. No folder created in the downloads folder.

How does one enable the backups? 

How does one know if the backup is enabled? Bold vs not bold?  

Can the name of the folder be chosen?

**Comment by Califauna** [comment]
Ok. I see the problem. The checkboxes weren't visible on my screens. 

Might want to make them a bit darker. They might get washed out easily low contrast or bright screen settings (based on what is visible on my two screens at least)

**Comment by Califauna** [comment]
> Also, if I want to easily and quickly transfer a single session to one of my other profiles, I just copy the sessionstore-backups folder, sessionCheckpoints.json, sessionstore.js, and sessionstore.js, and replace the matching items in the target folder.

This wont replace all the sessions will it?  I only want to recover a few.

**Comment by Califauna** [comment]
> sessionstore-backups folder, sessionCheckpoints.json, sessionstore.js, and sessionstore.js

This is a typo right?  You've written the same file twice.

I have created a new profile to see if i can get this to work. The profile is in the C: app data folder for some reason, whereas the profile that launches by default when i launch firefox portable is located in the data folder of the portable app folder.

Anyway, I installed tab session manager and no sessionstore.js file gets created in the profile directory.

Regardless, I copied the folder and two files you mention from my normal profile to the new profile. However, opening the tab session manager to look at the profiles, the sessions from my normal prfile aren't there, only one or two of the automatically created sessions in the new profile. 

Either somethings wrong here or I'm going to need more detailed instructions on how to do this.

**Comment by Califauna** [comment]
Also, backups are enabled but backup folder indicated is still not being created in download folder specified in firefox.

**Comment by nollinvoyd** [comment]
"This is a typo right? You've written the same file twice."

Yes.  My bad.

sessionstore-backups folder, sessionCheckpoints.json, sessionstore.js, and sessionstore.jsonlz4

After replacing the old with the new, restart the browser and the current tab session that is loaded will match the one from the other profile.  Of course, To back it up, you will have to enable the proper settings in TSM and reboot or do a manual backup from the TSM > sessions > export.  You also might want to "save" the current session by way of the TSM toolbar drop down menu.

"Anyway, I installed tab session manager in the new profile and no sessionstore.js file gets created in the profile directory"

You can transfer sessionstore-backups folder, sessionCheckpoints.json, sessionstore.js, and sessionstore.jsonlz4 to a fresh profile with "no" addons installed, and when you restart the browser, all the tabs will be displayed there.  Then, install TSM, adjust the settings to your liking, and after reboot the session should show up in the TSM toolbar menu, and be backed up as well to wherever that folder has been created.

If you have checked the box next to "TabSession Manager - Backup" folder, that should be creating the "TabSession Manager - Backup" folder.  Have you tried to do a file explorer "search" for the folder.  My guess is that you may find somewhere you don't expect.

**Comment by Califauna** [comment]
No I haven't tried a search. Isn't it supposed to be under the firefox downloads folder though? Thats what it says its limited to in TSM's options.

**Comment by Califauna** [comment]
There is no sessionstore.jsonlz4 in my old profile for some reason. It is there in the new profile I created though. However, opening the new profile, there are none of the old sessions.

Can we start again here? I just want one session really. I have some backups of the whole installation of portable firefox. In those isntalaltions, clicking on the TSM button does nothing (the dropdown flickers for a secon but too fast to read).  Clicking on the ' export' session  option in TSM does nothing at all.

In those backups however are the three files and folder you mentioned.How can I use them to get a copy of the sesion I need to recover?

**Comment by nollinvoyd** [comment]
Is this "old profile" you mention located within your Firefox portableapps folder?

When a regular version of Firefox ("regular" meaning other than portableapps) is first launched, by default, it will automatically create a fresh profile in that C: app data folder location you mentioned. 

However, that portableapps setup is self contained.  The profile folder is built-in, located in the "data" folder within that main portableapps directory.

IMO, you have something broken within that setup that has nothing to do with TSM.  It could very well be a bad profile, or something else altogether.  Whatever it is, that new profile in C: app data would never have been created If things were working properly.

Furthermore, Under normal circumstances, uninstalling and reinstalling Firefox should not wipe out the current session upon relaunch.  All the backups previously listed in the toolbar button menu will be missing, but the current sessions should remain intact.

Maybe I'm wrong, but I'm going to go out on a limb and assume the reason you thought your sessions were wiped out was because Firefox was bringing up the newly created profile from C: app data, which had nothing in it in the first place.  

Is this "old profile" you mentioned the one inside the portableapps directory?

Create a new Firefox portableapps setup.  After you launch it, a fresh profile will be created within that new portableapps directory.  Close the browser.  

Then try one or both of the next things. 

1) Replace the entire contents of the new portableapps profile with the old portableapps profile contents, and launch the new browser.  Best case scenario, the profile was not originally damaged, and your session will return, and things will go back to normal including all the backups listed in the toolbar button menu, if you had it TSM set to save them.

or  

2) Take only the sessionstore-backups folder, sessionCheckpoints.json, and sessionstore.js (don't worry about sessionstore.jsonlz4) of the old portableapps profile, and transfer them to the new portableapps profile, and launch the new browser.

**Comment by Califauna** [comment]
That link  goes to an empty Github page.

**Comment by Califauna** [comment]
OK I found it by searching.

**Comment by Califauna** [comment]
Resolved this problem as best I can now. I had multiple backups of firefox but the TSM window wouldn't open in any of them except one, which I eventually found. So used the export option and imported to new profile.

**Comment by Califauna** [comment]
Thabks for the reply.  The TSM session manager drop down menu not working
was fixed by reinstalling TSM. Never found out why the menu stopped
appearing.

The auto save function wasn't working because the checkbox to enable it
wasn't visible on my screen due to the contrast settings on my screen and
the fact that the checkbox is a colour that doesn't stand out much compared
to if it were black instead of light grey.
