### ISSUE TITLE
 Add "open session list in tab" to the right click menu or slap it on middle click

### ISSUE THREAD

**Issue by TinyTrbl** [sienori/Tab-Session-Manager#438]
Small UI enhancement(s).

**Describe the solution you'd like**
Add "**open session list in tab**" feature to the addon-button right click menu or allow to activate this feature with middle click on addon-button, maybe via checkbox in the addon options.

On a side note... why limit "**size of the popup**" in addon options with hardcoded values? Maybe you can allow something bigger than 800*600px area?

Also maybe you can allow to resize left-side-column? It became quite narrow after 5.0.0 changes.

I am leaving for now, hehe. Thank you again!

**Comment by sienori** [comment]
> Add "open session list in tab" feature to the addon-button right click menu or allow to activate this feature with middle click on addon-button, maybe via checkbox in the addon options.

I think it is unnecessary.

It is possible to add items to the right-click menu of add-on buttons.
However, it takes the same time to click the "Open session list in tab" button.
![openintab](https://user-images.githubusercontent.com/29514424/64511024-60525980-d31e-11e9-96e5-e7ad65377d45.png)
Also, There is no way to detect middle clicks on add-on buttons.

---

> On a side note... why limit "size of the popup" in addon options with hardcoded values? Maybe you can allow something bigger than 800*600px area?

Due to WebExtensions limitations, the pop-up size is limited to 800x600.

---

> Also maybe you can allow to resize left-side-column? It became quite narrow after 5.0.0 changes.

I will implement a function to adjust the width of the sidebar in the future.
