### ISSUE TITLE
Put "Open" and "Delete" links under every session name back to the session list.

### ISSUE THREAD

**Issue by buithehoa** [sienori/Tab-Session-Manager#447]
**Is your feature request related to a problem? Please describe.**
The session list used to includes "Open" and "Delete" links under every session name. On a daily basis, a typical user will only need to open a session or save a new version of a session and delete the old one. 

With the new UI update, the 2 links mentioned above were removed. Now a user has to select a session first to see "Open" and "Delete" links.

**Describe the solution you'd like**
Put the 2 links back to the session list or provide an option for that.

**Comment by sienori** [comment]
I plan to add open and delete buttons to the session list.

**Comment by buithehoa** [comment]
> I plan to add open and delete buttons to the session list.

Thank you so much.

**Comment by nollinvoyd** [comment]
I second the motion, but I have a question.

It's not uncommon for me to collect 50+ sessions in the list.  With the old setup, I could just repeatedly click-click-click on delete, leaving my mouse in the same position as the next session would move up to take the place of the deleted one, and in a matter of seconds, remove as many older session as I pleased.

But now, deleting just one session is painfully slow.  Not just because you have to reach over to the right button to delete, but then you have the delay before continuing.

Will bringing the open & deleted buttons back to their original position return the previous speed efficiency.  If not, maybe have an option to close that new side panel, if that would help speed things up?

thanks

**Comment by sienori** [comment]
I implemented open / delete buttons on the session list. https://github.com/sienori/Tab-Session-Manager/commit/9664c571baf2565d3f59b6f3920f2338e723061b
It can be disabled by option.
![open / delete buttons](https://user-images.githubusercontent.com/29514424/64638253-604a7a80-d440-11e9-90bd-5614685da872.png)

**Comment by futagoza** [comment]
@sienori close?

**Comment by candrapersada** [comment]
> I implemented open / delete buttons on the session list. [9664c57](https://github.com/sienori/Tab-Session-Manager/commit/9664c571baf2565d3f59b6f3920f2338e723061b)
> It can be disabled by option.
> ![open / delete buttons](https://user-images.githubusercontent.com/29514424/64638253-604a7a80-d440-11e9-90bd-5614685da872.png)

how to delete a session after opening automatically?
