### ISSUE TITLE
Cannot open my almost 10000 tabs session

### ISSUE THREAD

**Issue by TinyTrbl** [sienori/Tab-Session-Manager#575]
## Short description
Long story short - i successfully combined my year long small sessions to one huge session to find duplicate tabs and observe what do i have overall. Do not ask why, please. Well, i cannot fully open this session after i saved and closed it.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Make really big session, with 9700 non-empty tabs at minimum
4. Save that session, Exit Firefox
5. Try to re-open saved session 

## Expected result
Fully opened session

## Actual result
After 5+ minutes it can open up to 7230 from 9000+ tabs and then everything stops i.e. it no longer loads tabs. 
The browser becomes quite unstable after this point and crashes spontaneously if i navigate the interface and especially if click tab-related things (i.e. i cannot open List All Tabs menu it freezes for a while and crashes) 

## Platform information
* Platform (OS): Windows 10 64-bit
* Version of browser: Firefox 78.0.1 64-bit
* Version of Tab Session Manager: 6.1.0

## Additional context
I am not sure if this is addon or Firefox related bug. It might be addon, because it produces really big session files even with disabled favicons - 10,9 MB and 280264 text lines to store 9663 URLs, this is not a small amount of overhead and a lot if data to process...

**Comment by tab328** [comment]
I've noticed firefox 78 freezing with several thousands of tabs as well. It does load them all as far as I can tell before it freezes. If I export my session to a json, the resulting file is 175MB. You have to consider the window titles and other such things as well. Firefox 71 had no such trouble. Do you know if it's possible to downgrade and try with FF71?

**Comment by perXautomatik** [comment]
i have limit my sessions to be maximum 1000 it feels bit large anyway but but.
[answere on stackoverflow](https://stackoverflow.com/a/48411411) might help you to extract the session to json, then you could trim it down to small size, and import it again with the extension from developer console.

i moved to this sessionmanager when i noticed my browsers automatically trimmed my history data, and i think it's due to the sizelimitations that this trimming occurs.

my forte is closer to relational databases, and i think the internal database for browserextensions tends to be a flat strutuctured data, i imagine, get rather heavy for larger datasets. 
maybe if sessionManager could apply some sort of compressionalgorithm. 

might i ask what you people use your data for? 
i personaly use it for datavizualisation and other datasientifical experiments.

i think it would be rather usefull if sessionmanager would have some dedupefeature, but that might be easier said than done

**Comment by sienori** [comment]
I've implemented the ability to compress the favicon url when saving the session. 1c6ac8a #471
This update saves memory usage and storage space by compressing the favicon URL.

Opening a huge session with 10000 tabs requires a powerful machine. I do not recommend it.
