### ISSUE TITLE
Auto cloud sync? Current session and tab management? Smart auto save?

### ISSUE THREAD

**Issue by snovvmann** [sienori/Tab-Session-Manager#602]
Hi, thanks for a great product. I have some questions and requests: 

1) Is the cloud sync automatic (based on time or some trigger) or does it require me to press the cloud icon on the upper right side? It seems like when there is an exclamation mark on the cloud icon, there is unsynced data, but it does not auto sync. It would be great if it can auto sync. 

2) Much like Session Buddy, Tab Outliner, or Cluster Tab Manager, it would be great if Tab Session Manager allowed for current session and tab management where I can see all the open windows and tabs, close them as needed, and move the tabs between windows. Currently, TSM only allows for management of sessions that are already saved. The missing feature for me is to be able to manage the current session because it would allow me to eliminate the need for other extensions for this functionality. 

3) It would be nice if TSM, before saving based on timed intervals, *not* save the session if none of the windows or tabs have changed. In other words, if the computer is sitting idle, there is no need to re-save the same sessions. 

I would appreciate a response and your thoughts. I would be very glad to become a backer if you are able to address some or all of these items.

Again, thank you.

**Comment by Mysteerion** [comment]
+1 for auto sync!
On my side, when I click on the sync button when having an exclamation mark, either sync goes well and the exclamation mark disappears, or my Google credentials are asked before I can sync. However, Chrome sync is enabled and working. This happens whether cookies are cleaned or not on browser exit. Can you help? Thanks a lot!

**Comment by jaepil-choi** [comment]
Cloud sync is the most wanted feature for me. Hope he doesn't lose interest in this product. 
I personally backed him $10 to fund his project. Tab Session Manager is being used by so many people but only 2 people were funding him via Github Sponsor regularly. Since regular sponsorship was too much for me, I decided to back him with one-time payment. 
I don't know if my funding will help him implement could sync feature but hope it boosts up the progress.

**Comment by perXautomatik** [comment]
might be irrelevant but
would backup to gist be a alternative?

**Comment by petko10** [comment]
Just to add to the discussion - it would be nice to have an option to receive a "Replace/add latest session to the current one"  or even directly apply the latest received remote update, similar to the Real-time tab sync extension (that, disclaimer, I'm the author of).

**Comment by sienori** [comment]
I added the auto sync option! https://github.com/sienori/Tab-Session-Manager/commit/31346439f654654789574ef5c0044eac50d13cc2
![image](https://user-images.githubusercontent.com/29514424/114171875-de019f80-996f-11eb-9ce7-2b6bd7db5b20.png)

**Comment by perXautomatik** [comment]
> Just to add to the discussion - it would be nice to have an option to receive a "Replace/add latest session to the current one" or even directly apply the latest received remote update, similar to the Real-time tab sync extension (that, disclaimer, I'm the author of).

Oh sheeeet would be soo cool if you two could join the repos somehow!

**Comment by petko10** [comment]
@perXautomatik alas it's not that straight forward. My code is a bit of a mess, and is not portable across browsers. It doesn't even work on Chromium anymore, since Google disabled its sync service there. That's one of the reasons I was looking to deprecate my extension fully and refer the users to TSM. That's still under consideration though, since some users voiced concerns that the functionality is still not covered. It would be fully understandable if sienori doesn't implement auto-replace/add for sessions, since it's quite the unstable feature (though if optional - some users like it). Even on RTTS where that's the main feature advertised, I consider it unstable, since some websites have problems with it - be it on login, or other types of redirect, or auto-refresh, where the URL changes.

**Comment by jaepil-choi** [comment]
> I added the auto sync option! https://github.com/sienori/Tab-Session-Manager/commit/31346439f654654789574ef5c0044eac50d13cc2
> ![image](https://user-images.githubusercontent.com/29514424/114171875-de019f80-996f-11eb-9ce7-2b6bd7db5b20.png)
> 

OMG! Thanks so much for tracking the feature suggestion. Recommended this app to many friends and they are lovin it.
