### ISSUE TITLE
External API to open session?

### ISSUE THREAD

**Issue by Putr** [sienori/Tab-Session-Manager#736]
**Is your feature request related to a problem? Please describe.**
I'm writing a bash tool to manage coding sessions and would like to add the ability to use Tab Session Manager to save tabs related to the coding session/project and open it when you open the session/project.

**Describe the solution you'd like**
An API (implementation of documentation/direction) that a bash script can trigger to open a session (closing would be a plus).

**Describe alternatives you've considered**
Tried searching for documentation ... honestly don't know what to search for apart from "API".

Thank you,
Grateful long time user of Tab Session Manager on FF.

**Comment by sienori** [comment]
Since WebExtensions cannot receive messages from external applications, the API cannot be provided.
If you can simulate keyboard input from the bash, you may be able to use keyboard shortcuts to save and open sessions.
![image](https://user-images.githubusercontent.com/29514424/116050430-6b542c00-a6b2-11eb-86b8-a0069ebbe2ee.png)
