### ISSUE TITLE
 Delete button size

### ISSUE THREAD

**Issue by bandaid** [sienori/Tab-Session-Manager#744]
Delete button size #743 

Larger screens 4K plus... smaller windows and dialogs. 

Please update

**_Original dialog_**. Icons are too small and present all sorts of problems. Previous ticket#[741](https://github.com/sienori/Tab-Session-Manager/discussions/741) requesting to add confirmation dialog prior to the opening session. Also, no need for the 'Open' icon and dialog because when you click on the list to the left it opens anyway. It's just user-friendly than being cumbersome. 

![2021-04-12 18_18_44-](https://user-images.githubusercontent.com/8212255/114477577-eb2ac280-9beb-11eb-9115-d7924ffd787b.png)
.
.
.
.
### User should have a choice in Tab Session Manager 'Settings' for single or double width.
.
.
.
.
**New dialog with single width delete scaled to list item**

![single_size](https://user-images.githubusercontent.com/8212255/114477588-ef56e000-9beb-11eb-9cf2-be1ea8608d2a.png)
.
.
.
.
**New dialog with double width delete scaled to list item**

![double_size](https://user-images.githubusercontent.com/8212255/114477604-fa117500-9beb-11eb-824f-32cb8baa986b.png)

**Comment by sienori** [comment]
Thanks for the request!
I have improved the style of the open and delete buttons. https://github.com/sienori/Tab-Session-Manager/commit/7d4c71f47336cbbc1c731b0f9b2be101d2451e4f
The buttons have been enlarged and the animation has been improved so that it does not affect pointing.
![Screen Shot 2021-04-26 at 20 11 35](https://user-images.githubusercontent.com/29514424/116073652-a878e800-a6cb-11eb-9877-f28107dbff99.png)

The Open button can be substituted with a double-click, but it is necessary for discoverability.

**Comment by bandaid** [comment]
Thank you very much. It is significantly more manageable now!

**Comment by davidp88** [comment]
still it is small,don't enlarge
