### ISSUE TITLE
Double-click to open session when deleting + slowness on open

### ISSUE THREAD

**Issue by i2324561w2** [sienori/Tab-Session-Manager#745]
## Platform information
* Platform (OS): Windows10
* Version of browser: FFv87.0 (64 bit)
* Version of Tab Session Manager: 6.5.0

Before the new "Double-click to open session" I often deleted a bunch of sessions from the second top using the trash icon, but now if I click too fast it will open a session instead of deleting it.

Also (and this was introduced a looong time ago) when I click on the icon on the addons toolbar to open this addon, there is a freeze of even 2 second (I suppose it depends on the number of tabs in a saved session) because it will automatically select a session, but the opening is very fast if no session is automatically selected (for example if I first delete the selected session).

I hope you can make this addon even better, thank you.

**Comment by bandaid** [comment]
Already been mentioned multiple times see [744](https://github.com/sienori/Tab-Session-Manager/issues/744)

**Comment by sienori** [comment]
Thanks for the report!
I fixed the issue of accidentally opening a session when clicking the delete button repeatedly. https://github.com/sienori/Tab-Session-Manager/commit/7d4c71f47336cbbc1c731b0f9b2be101d2451e4f
The buttons have been enlarged and the animation has been improved so that it does not affect pointing.
![Screen Shot 2021-04-26 at 20 11 35](https://user-images.githubusercontent.com/29514424/116073652-a878e800-a6cb-11eb-9877-f28107dbff99.png)
