### ISSUE TITLE
Restoring tab group does not restore its names

### ISSUE THREAD

**Issue by cherian** [sienori/Tab-Session-Manager#753]
https://d.pr/i/6lxhrS 

I ended up getting empty groups.

**Comment by sienori** [comment]
In order to save and restore tab groups, you need to enable `Save tab groups` option and install an additional extension: https://chrome.google.com/webstore/detail/save-tab-groups-for-tab-s/aghdiknflpelpkepifoplhodcnfildao
![image](https://user-images.githubusercontent.com/29514424/116048454-27602780-a6b0-11eb-9b82-8fd4780ecf5f.png)

**Comment by TheOverpassArsonist** [comment]
Also on brave and even with the Save Tab Group extension tab names are not saved. (it appears tab colours are though)

**Comment by devanteweary** [comment]
I'm on Brave as well.
[Version 1.65.122 Chromium: 124.0.6367.82 (Official Build) (64-bit)]

I have the exact same issue: tab group names restore as blank. 
I have installed both TSM and the Save Tab Groups extension.

**Comment by TheOverpassArsonist** [comment]
For future reference, when I originally had this issue I glanced at the code a bit and wrote #1266 which I believe fixes it. It's a small enough change that it can be applied manually by downloading the extension, applying the modifications, and then enabling dev mode and loading the modified extension locally.

The issue is that in tracking mode group information is not properly saved, but _is_ properly saved with manual saves. It's not that they're not restoring properly, it's that they're not being saved properly when tracking mode saves them.
