### ISSUE TITLE
TSM & Overflow Menu/More Tools dropdown window doesn't fit

### ISSUE THREAD

**Issue by 2mg** [sienori/Tab-Session-Manager#778]
## Short description
Using the Overflow Menu in Firefox to access TSM makes it simply not fit in it, unlike other addons.

## Steps to reproduce
Simply customize Firefox and try to use TSM from Overflow menu, it's unusable.

## Expected result
Overflow menu expanding to accommodate TSM GUI.

## Actual result
![tsm](https://user-images.githubusercontent.com/7749968/118524292-4c3f3c00-b73e-11eb-9821-5cedb4d2d550.jpg)

## Platform information
* Platform (OS): W7, W10
* Version of browser: FF 88.0.1 (64-bit)
* Version of Tab Session Manager: 6.7.0, 6.8.0 (any).

## Additional context
Either FF Overflow menu should expand to fit TSM GUI, or TSM GUI needs a rework to fit into Overflow menu. Also, using the middle click scrolling doesn't allow horizontal scrolling to see the cut parts of the GUI.

**Comment by sienori** [comment]
This is due to a issue in Firefox. https://github.com/sienori/Tab-Session-Manager/issues/436

I have made the popup scrollable horizontally. https://github.com/sienori/Tab-Session-Manager/commit/ad7771e9ac8a5af740b6d23f50d3ac3a9bfa2b8d
![image](https://user-images.githubusercontent.com/29514424/120101395-e1035a00-c180-11eb-8a09-c830adf344ff.png) https://github.com/sienori/Tab-Session-Manager/commit/ad7771e9ac8a5af740b6d23f50d3ac3a9bfa2b8d

**Comment by 2mg** [comment]
I can barely get horizontal scroll icon to appear, and when it does, it doesn't scroll horizontally though...
