### ISSUE TITLE
Edge v.6.8.1. Tabs in restored sessions don't fully open (don't show back/fwd history of each tab).

### ISSUE THREAD

**Issue by txtxtx111111** [sienori/Tab-Session-Manager#795]
Is v6.8.2 available for Edge? Maybe that would fix my problem? Tabs in restored sessions only show an intermediate file that contains the url of the tab. And any back/fwd history for the tabs is lost.

**Comment by txtxtx111111** [comment]
Current version of Microsoft Edge is Version 91.0.864.37 (Official build) (64-bit).

**Comment by sienori** [comment]
Version 6.8.2 for Edge will be available with in a few days.
The problem of lazy loading of tabs will be fixed. https://github.com/sienori/Tab-Session-Manager/issues/784
I don't plan to implement the back/forward history because it is not supported by WebExtensionsAPI. https://github.com/sienori/Tab-Session-Manager/issues/27

**Comment by 1v** [comment]
Still not updated?

**Comment by 1v** [comment]
Update took more than week 😞.

**Comment by sienori** [comment]
There has been a delay in the review process in Edge.
It will be released within a week.
