### ISSUE TITLE
Backup option to download everything instead of incremental download

### ISSUE THREAD

**Issue by haoadoresorange** [sienori/Tab-Session-Manager#856]
**Context**
I configure my TSM to auto-save sessions and keep only a limited number of them. I want to use the backup function to mirror the exact same thing on my filesystem. But because the TSM cannot cleanup old sessions on the filesystem once its downloaded, it floats the backup folder with the entire history of all backups. So I tried to run a cronjob to `rsync --delete --delete-sources` from the downloaded backup folder. However this doesn't work either because TSM "incremental" downloads the sessions (aka it only downloads what hasn't been downloaded from the current state). My rsync with --delete option delete everything else in the destination folder.
If I don't use the --delete option we're back to square one where it keeps the entire history.

**Describe the solution you'd like**
Add an option to download the entire state every backup (overwrite same name).

**Comment by sienori** [comment]
I don't think the method of keeping a single backup file by overwriting it works well enough.
If a portion of the session is lost due to a browser crash, the backup file will be overwritten with lost sessions. This means that the backup is useless.

To avoid bloated backups, it is a good idea to disable the individual backup option and run a command that deletes past backup files.
https://superuser.com/questions/268344/how-do-i-delete-all-but-10-newest-files-in-linux/268345
![individual backup option](https://user-images.githubusercontent.com/29514424/132469102-7c320e4b-d52a-4233-a513-608d558c06a7.png)
