### ISSUE TITLE
Close (or clean) Tabs that is not part of the sesion

### ISSUE THREAD

**Issue by oliverhartley** [sienori/Tab-Session-Manager#883]
**Describe the solution you'd like**
Hi, I would like to maintain a specefic sesion with just my work tabs, and be able to close or move all other tabs to another session so i can maintain a "clean" working sesion. 

**Describe alternatives you've considered**
I have been using tabli, that makes what i need but its not been updated any more

**Additional context**
Usually i start my day with two chrome sesion, one with my calendar (only that tab) to make it visible all the time, and i actually move it a a separate screen. And a second Sesion, with mail, chat, github..... the second sesion as hours pass by start accumulating lots of tabs, i would like with one click, clean everithing and go back to the "original state" so i can maintain a "clean" sesion. Same think with my calendar sesion.... I usualy end the day with a third sesion, wich is the "dirty one". Hope it makes sense.

**Comment by sienori** [comment]
You can use "Open in current window" feature. This will close all currently open windows and tabs, and open the specified session. Since version 6.11.0, the tabs that are closed at this time are saved as an autosave session. https://github.com/sienori/Tab-Session-Manager/commit/a587cee41bd4d1ddfad84324b04d57c63977f41d
![image](https://user-images.githubusercontent.com/29514424/136750487-1107adee-a1f2-490f-98fc-335f5e01b693.png)
