### ISSUE TITLE
Local files cannot be restored (on Linux)

### ISSUE THREAD

**Issue by MarcClaessens** [sienori/Tab-Session-Manager#931]
## Short description
I have a local HTML file which I use as a portal page (i.e. it stores my favorite, commonly visited web sites).
I find however that my HTML file can not be opened by Tab Session Manager when on Linux (my home PC).
However the same file on Windows (my work laptop)  can be opened.

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Create a simple test.html file on the Desktop:
```
<head></head>
<body>
	<h2>Test</h2>
</body>
```

4. Open the file with Firefox
5. Restart Firefox

## Expected result
The test.html file is opened and shows the heading "Test"

## Actual result

Visible text :

### /home/marc/Desktop/test.html
file:///home/marc/Desktop/test.html
[Copy URL](url)
This page can not be opened by Tab Session Manager.

HTML body :
```
<body data-theme="light">
  <div class="container">
   <div class="title">/home/marc/Desktop/test.html</div>
   <input class="replacedUrl caption" value="about:example"> 
   <a class="copyButton">Copy URL</a>
  <div class="replacedPageMessage caption">This page can not be opened by Tab Session Manager.</div></div>
</body>
```
Note 1 : if I copy the URL and paste it, then Firefox opens it without problem
Note 2 : the URL bar contains :

moz-extension://40f5b4cd-859d-46f8-9266-072e9a3be5c0/replaced/index.html?state=open_faild&title=%2Fhome%2Fmarc%2FDesktop%2Ftest.html&url=file%3A%2F%2F%2Fhome%2Fmarc%2FDesktop%2Ftest.html&favIconUrl=undefined&theme=light

## Platform information
* Platform (OS): Ubuntu 21.10
* Version of browser: Firefox 95.0.1 (64-bit)
* Version of Tab Session Manager: 6.11.1

**Comment by andoruB** [comment]
Can confirm this at my end as well.

**Comment by ninmonkey** [comment]
## Maybe the source?

Below, `state=open_faild` seems to be the trigger, and that is being added right here:
- [openUrl.js](https://github.com/sienori/Tab-Session-Manager/blob/908a08c8705be60478093ba3950ddf3f20e9d9a9/src/popup/actions/openUrl.js#L11)

You could try removing the param

## otherwise 

Windows will not restore tabs using the `file://` protocol on my local machine.
Often browser APIs will limit local file access, for security reasons.

## Maybe easily editable? About:Config

It's probably an `about:config` setting, or `userprefs.js` maybe `security.fileuri.strict_origin_policy` ? It didn't seem to do anything, but, the code itself doesn't seem to catch all errors. (see below)

If you have two different machines, both running the same versions, and one view local and not the other, check the group policies. `File` may be used in `WebsiteFilter`

- [https://github.com/mozilla/policy-templates#websitefilter](https://github.com/mozilla/policy-templates#websitefilter)

## A simple workaround I use for my speed dial is

- set "homepage" to my `file://` page, and
- set "new tabs" to my file
----
![image](https://user-images.githubusercontent.com/3892031/173471951-c24063e5-812e-4bc8-98bf-ef760199f353.png)
----
This lets me get my custom speed dial if I use any of these

- click home toolbar icon
- `ctrl+n` a new window, or
- use the [alt+home](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) hotkey (TIL)

I use that setup because I have it set to auto restore my previous session on load

## First git clone the addon, then

I greped for `This page can not be opened by Tab Session Manager`
```ps1
src\_locales\en\messages.json
786:    "message": "This page can not be opened by Tab Session Manager."
```
[src\_locales\en\messages.json](https://github.com/sienori/Tab-Session-Manager/blob/55fbfd13c363743be43919c2455505850d01c8ea/src/_locales/en/messages.json#L785-L786)

taking me to 

[https://github.com/sienori/Tab-Session-Manager/blob/4deea756914a9838f001b1bdd83c26ed95b7dea3/src/replaced/replaced.js#L49-L52](https://github.com/sienori/Tab-Session-Manager/blob/4deea756914a9838f001b1bdd83c26ed95b7dea3/src/replaced/replaced.js#L49-L52)

Now find `open_faild`

![image](https://user-images.githubusercontent.com/3892031/173473708-65a559b7-e480-4297-8484-93bdbb59621f.png)

**Comment by MimmyJau** [comment]
Can confirm that this is a problem on macOS (tested with both local pdfs and html files). [MarcClaessens](https://github.com/MarcClaessens) I'm surprised you were able to get it to work on Windows since, from my understanding, this is a Firefox Security Issue.

I found a workaround [here](https://github.com/fastaddons/GroupSpeedDial/issues/36#issuecomment-788283828) that helped solve the problem. One must go to `about:config` (just type it into the url) and add the following settings:

```
capability.policy.policynames = "localfilelinks"
capability.policy.localfilelinks.checkloaduri.enabled = "allAccess"
capability.policy.localfilelinks.sites = "moz-extension://UNIQUE_ID_OF_TAB_SESSION_MANAGER"
```

Two notes:

1.  The `UNIQUE_ID_OF_TAB_SESSION_MANAGER` will be different on every computer. The easiest way of finding it is to just look at the URL of the tab that failed to load. It should look like:

`moz-extension://UNIQUE_ID_OF_TAB_SESSION_MANAGER/replaced/index.html?state=open_faild&title=....`

Alternatively, you can go to the settings page for Tab Session Manager, and you'll see something similar in the URL:

`moz-extension://UNIQUE_ID_OF_TAB_SESSION_MANAGER/options/index.html`

2. When adding the three lines above to `about:config` you first type what's on the left side of the equation (e.g. `capability.policy.policynames`) then select `string` and then type in the what's on the right hand side of the equation (e.g. `localfilelinks` without double quotes). Note, this is at least what the UI looks like on macOS Firefox (not sure about Windows or Linux).

Other sources suggesting this is a Firefox Security Issue:
- https://wiki.mozilla.org/WebExtensions/Filesystem
- http://kb.mozillazine.org/Firefox_:_Issues_:_Links_to_Local_Pages_Don't_Work
- https://discourse.mozilla.org/t/opening-links-to-local-files-file/16449
- https://discourse.mozilla.org/t/how-to-access-local-files-from-an-extension/92190

**Comment by MarcClaessens** [comment]
Excellent, that fixed my issue !
Thank you MimmyJau :)

**Comment by Obscure2020** [comment]
Recently ran into the same issue. MimmyJau's instructions did the trick perfectly.

Out of curiosity, is there no way the addition of these settings could be automated during the installation process? Or performed by a button in the settings menu?

**Comment by sienori** [comment]
@Obscure2020 It would not be possible to configure `about:config` from webExtensions...
