### ISSUE TITLE
Tabs not opening 

### ISSUE THREAD

**Issue by 1RonRock** [sienori/Tab-Session-Manager#99]
When I try to open a saved session the tabs "seem" to be opening, but when I click on them I see a white page with the page address, not the page.
![2017-12-06](https://user-images.githubusercontent.com/34315473/33676704-1751eaf8-da7c-11e7-98fb-ecbfee8d21e3.png)

**Comment by sienori** [comment]
Normally, when all the tabs are opened, the page is replaced.
Does the same thing happen in another session?

**Comment by aaaxx** [comment]
This happens to me too. I imported Session Manager's .session file with 314 tabs, and when I try to open them, it only opens 13 tabs, and they're just blank pages with title and address.

I also tried importing a smaller session file, with just four tabs, and opening them worked as expected.

**Comment by sienori** [comment]
@aaaxx Can you provide a problematic file?

**Comment by aaaxx** [comment]
Sorry, can't do it for privacy concerns, but I did some digging and figured out what's causing it.

Comparing the Session Manager's .session file to your `storage.js`, I noticed that you read the tabs' `"ID"` keys and use them as IDs in Tab Session Manager. So, you can probably guess what happens. Session Manager's IDs aren't unique, and the first of the tabs with duplicate IDs gets dropped when importing.

Tab Session Manager then reports the correct number of tabs in the interface, but won't show the list of tabs when you click "<var>n</var> Windows - <var>n</var> Tabs".

Then when it starts opening the session, it gets to the missing `"index"` number (caused by the missing tab object in `storage.js`) and stops opening the rest of the tabs, which somehow blocks the already opened tabs from being able to load.

The simple fix would be to just use a counter to generate tab IDs when you're importing them.

I made you a [test file](https://pastebin.com/gUUYHc2Q) and tried to remove as much of unnecessary Session Manager properties as possible. ([Minified version is here](https://pastebin.com/xTXcRUtL), since that's all that Tab Session Manager recognizes.)

There are three tabs – Google, GitHub & New York Times – with IDs **1**, **2**, **2**. After you import the file, you'll see in your `storage.js` that GitHub is missing. You only have Google and NYT, with indexes 0 and 2. When you try to open the session, only Google's tab will open, and it will fail to load.

Now change the New York Times' `"ID"` to **3** (line 5, column 1023 in the minified file), import it again, and it will work as expected.

**Comment by sienori** [comment]
Thanks @aaaxx!
I solved the problem of ID duplication and the problem that the replacement page can not be replaced.
https://github.com/sienori/Tab-Session-Manager/commit/ca58887f225c8152de08aca48974f26962b77cfd
https://github.com/sienori/Tab-Session-Manager/commit/129276b7590f65edb60e39cd1c1effa38d59325a
